# tests/delayed_disambiguation_1d_double_well_master.py
#
# Master script: 1D double-well delayed-disambiguation synthetic + PF analysis.
# - Switches to turn each test/plot on/off
# - Saves plots + arrays + config to results/_synthetic_1d_double_well_analysis/<run_name>/
# - Uses *potential-based* double-well parametrization by default:
#       V(z) = (lambda/4) (z^2 - a^2)^2
#       drift = -dV/dz = -lambda * z * (z^2 - a^2)
#       z_{t+1} = z_t + dt * drift(z_t) + sigma * eps
#
# Usage examples:
#   python tests/delayed_disambiguation_1d_double_well_master.py --help
#
#   # default run (saves everything)
#   python tests/delayed_disambiguation_1d_double_well_master.py
#
#   # only generate + PF + heatmaps + branch mass, skip heavy diagnostics/sweeps
#   python tests/delayed_disambiguation_1d_double_well_master.py \
#       --no-diagnostics --no-sensitivity --no-forecast
#
#   # change well geometry + emission gating band
#   python tests/delayed_disambiguation_1d_double_well_master.py \
#       --a 1.2 --lambda 1.0 --dt 0.06 --process-noise 0.18 --emit-noise 0.22 --eps 0.45
#
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import matplotlib.pyplot as plt

from data.synthetic_generator import (
    GaussianPrior, GaussianTransition, GaussianEmission, generate_sequences
)

# ============================================================
# 0) Config
# ============================================================

@dataclass
class Config:
    # data
    T: int = 90
    dz: int = 1
    B: int = 1
    seed_data: int = 0

    # PF
    N: int = 30000
    seed_pf: int = 123
    resample_every: int = 3  # 1 = every step, 0 = never

    # potential-based double-well dynamics
    a: float = 1.0          # attractor locations +/- a
    lam: float = 1.0        # lambda (curvature / barrier height with a)
    dt: float = 0.06        # discrete-time step
    process_noise: float = 0.18  # sigma

    # emission
    emit_noise: float = 0.20
    emission_mode: str = "gated_linear"  # ["gated_linear", "band_evenpower", "tanh_saturate"]
    eps: float = 0.50        # gating band for x2
    n_even: int = 2          # for band_evenpower: x2=(z/eps)^(2n) inside
    k_tanh: float = 2.5      # for tanh_saturate

    # analysis knobs
    left_thresh: float = 0.05
    heatmap_bins: int = 220
    heatmap_zclip_lo: float = 0.5   # percentile for auto-range
    heatmap_zclip_hi: float = 99.5  # percentile for auto-range

    # heavy/optional analysis controls
    do_heatmaps: bool = True
    do_observation_plots: bool = True
    do_branch_mass: bool = True
    do_ess: bool = True
    do_evidence: bool = True
    do_forecast_divergence: bool = True
    do_sensitivity: bool = True
    do_diagnostics: bool = False  # dip / silverman-style are optional and expensive

    # forecast divergence
    t_star: int = 55
    H_forecast: int = 20

    # sensitivity sweeps
    resample_grid: Tuple[int, ...] = (0, 1, 2, 3, 5, 10)
    N_grid: Tuple[int, ...] = (2000, 5000, 10000, 30000)

    # saving
    results_root: str = "results"
    subfolder: str = "_synthetic_1d_double_well_analysis"
    run_name: str = ""  # if empty, autogenerated


def _autoname(cfg: Config) -> str:
    # Compact and deterministic-ish name
    return (
        f"T{cfg.T}_N{cfg.N}_re{cfg.resample_every}"
        f"_a{cfg.a:g}_lam{cfg.lam:g}_dt{cfg.dt:g}"
        f"_q{cfg.process_noise:g}_r{cfg.emit_noise:g}"
        f"_{cfg.emission_mode}"
        f"_eps{cfg.eps:g}"
        f"_sd{cfg.seed_data}_spf{cfg.seed_pf}"
    )


# ============================================================
# 1) Potential-based double-well transition + emissions
# ============================================================

def trans_mean_potential(z_prev: np.ndarray, extras: Dict) -> np.ndarray:
    """
    Potential: V(z) = (lam/4) (z^2 - a^2)^2
    Drift: -dV/dz = -lam * z * (z^2 - a^2)
    Euler step: z_next_mean = z + dt * drift
    """
    a = float(extras["a"])
    lam = float(extras["lam"])
    dt = float(extras["dt"])
    z = z_prev
    drift = -lam * z * (z**2 - a**2)
    return z + dt * drift

def trans_cov_isotropic(z_prev: np.ndarray, extras: Dict) -> np.ndarray:
    sigma = float(extras["process_noise"])
    dz = z_prev.shape[-1]
    return (sigma**2) * np.eye(dz)

def emit_mean(z: np.ndarray, extras: Dict) -> np.ndarray:
    """
    dx=2, stationary, nonlinear.

    Always:
      x1 = z^2  (sign-destroying)

    x2 depends on emission_mode:

      - gated_linear:
          x2 = z          if |z| < eps
               0          otherwise

      - band_evenpower:
          x2 = (z/eps)^(2n)  if |z| < eps   (kills sign strongly near 0)
               z            otherwise       (reveals sign)

      - tanh_saturate:
          x2 = tanh(k z)     (sign-revealing but saturating)
        (This is usually *not* delayed-disambiguation; kept as an alternate stress test.)
    """
    mode = str(extras["emission_mode"])
    eps = float(extras["eps"])
    z1 = z[:, :1]

    x1 = z1**2

    if mode == "gated_linear":
        x2 = np.where(np.abs(z1) < eps, z1, 0.0)

    elif mode == "band_evenpower":
        n = int(extras["n_even"])
        inside = (np.abs(z1) < eps)
        x2_inside = (z1 / (eps + 1e-12)) ** (2 * n)   # even power, kills sign
        x2_outside = z1                                # reveals sign
        x2 = np.where(inside, x2_inside, x2_outside)

    elif mode == "tanh_saturate":
        k = float(extras["k_tanh"])
        x2 = np.tanh(k * z1)

    else:
        raise ValueError(f"Unknown emission_mode='{mode}'")

    return np.concatenate([x1, x2], axis=1)

def emit_cov_isotropic(z: np.ndarray, extras: Dict) -> np.ndarray:
    r = float(extras["emit_noise"])
    dx = 2
    return (r**2) * np.eye(dx)


# ============================================================
# 2) PF utilities: Gaussian logpdf + bootstrap PF + evidence logging
# ============================================================

def log_gaussian_full(x: np.ndarray, mu: np.ndarray, cov: np.ndarray) -> np.ndarray:
    """
    x, mu: (N, d)
    cov: (d,d) or (N,d,d)
    returns: (N,)
    """
    x = np.asarray(x, dtype=float)
    mu = np.asarray(mu, dtype=float)
    d = x.shape[-1]

    cov = np.asarray(cov, dtype=float)
    if cov.ndim == 2:
        cov = np.broadcast_to(cov, (x.shape[0], d, d))

    out = np.empty((x.shape[0],), dtype=float)
    const = -0.5 * d * np.log(2.0 * np.pi)
    for i in range(x.shape[0]):
        L = np.linalg.cholesky(cov[i])
        y = np.linalg.solve(L, x[i] - mu[i])
        maha = float(y @ y)
        logdet = float(2.0 * np.sum(np.log(np.diag(L))))
        out[i] = const - 0.5 * (logdet + maha)
    return out

def systematic_resample(w: np.ndarray, rng: np.random.Generator) -> np.ndarray:
    N = len(w)
    positions = (rng.random() + np.arange(N)) / N
    cumsum = np.cumsum(w)
    return np.searchsorted(cumsum, positions)

@dataclass
class PFOutputs:
    z_filt: List[np.ndarray]          # length T: particles at time t (pre-resample), shape (N,1)
    w_filt: List[np.ndarray]          # length T: weights at time t (pre-resample), shape (N,)
    z_pred: List[np.ndarray]          # length T-1: predictive particles for z_{t+1} given x_{<=t}, shape (N,1)
    ess: np.ndarray                   # (T,)
    log_evidence: np.ndarray          # (T,) approx log p(x_t | x_{<t})
    cum_log_evidence: np.ndarray      # (T,) cumulative sum
    log_odds_pred: np.ndarray         # (T,) log((1-m_left_pred)/m_left_pred)
    log_odds_filt: np.ndarray         # (T,) log((1-m_left_filt)/m_left_filt)

def bootstrap_pf(
    x_seq: np.ndarray,
    prior: GaussianPrior,
    transition: GaussianTransition,
    emission: GaussianEmission,
    *,
    N: int,
    seed: int,
    extras: Dict,
    resample_every: int,
) -> PFOutputs:
    """
    Bootstrap PF (proposal = transition). Stores weights so filtering is meaningful.

    Evidence increment at time t:
      log p(x_t | x_{<t}) ≈ log sum_i w_{t-1}^i p(x_t | z_t^i)
    Here we compute it using the *current* particle cloud z (before weight update)
    and the previous weights w.

    Predictive left-mass uses the predictive particles (z_pred_curr).
    Filtering left-mass uses the weighted posterior at time t.
    """
    rng = np.random.default_rng(seed)
    T, dx = x_seq.shape
    dz = int(np.asarray(prior.mu0).shape[0])

    # init from prior
    z = rng.multivariate_normal(mean=np.asarray(prior.mu0), cov=np.asarray(prior.cov0), size=N)  # (N,dz)
    w = np.ones(N, dtype=float) / N

    z_filt: List[np.ndarray] = []
    w_filt: List[np.ndarray] = []
    z_pred: List[np.ndarray] = []

    ess = np.zeros((T,), dtype=float)
    log_evidence = np.zeros((T,), dtype=float)
    log_odds_pred = np.zeros((T,), dtype=float)
    log_odds_filt = np.zeros((T,), dtype=float)

    # predictive particles for current t (z_t | x_{<t})
    z_pred_curr = z.copy()

    eps_lr = 1e-12

    for t in range(T):
        # predictive branch mass at time t
        mleft_pred = float(np.mean(z_pred_curr[:, 0] < 0.0))
        log_odds_pred[t] = np.log((1.0 - mleft_pred + eps_lr) / (mleft_pred + eps_lr))

        # likelihood for current particle cloud
        mu_x = np.asarray(emission.mean_fn(z, extras), dtype=float)  # (N,dx)
        cov_x = np.asarray(emission.cov_fn(z, extras), dtype=float)  # (dx,dx) or (N,dx,dx)
        xt_rep = np.repeat(x_seq[t:t + 1], N, axis=0)                # (N,dx)
        loglik = log_gaussian_full(xt_rep, mu_x, cov_x)              # (N,)

        # log evidence increment: log sum_i w_i * exp(loglik_i)
        maxlog = float(np.max(loglik))
        log_evidence[t] = maxlog + np.log(np.sum(w * np.exp(loglik - maxlog)) + 1e-12)

        # weight update
        w = w * np.exp(loglik - maxlog)
        w = w / (w.sum() + 1e-12)

        ess[t] = 1.0 / np.sum(w**2)

        # store filtering posterior BEFORE resample
        z_filt.append(z.copy())
        w_filt.append(w.copy())

        # filtering branch mass
        mleft_filt = float(np.sum(w * (z[:, 0] < 0.0)))
        log_odds_filt[t] = np.log((1.0 - mleft_filt + eps_lr) / (mleft_filt + eps_lr))

        # resample
        if resample_every > 0 and ((t + 1) % resample_every == 0):
            idx = systematic_resample(w, rng)
            z = z[idx]
            w = np.ones(N, dtype=float) / N

        # propagate
        if t < T - 1:
            mu_z = np.asarray(transition.mean_fn(z, extras), dtype=float)  # (N,dz)
            cov_z = np.asarray(transition.cov_fn(z, extras), dtype=float)  # (dz,dz) or (N,dz,dz)
            if cov_z.ndim == 2:
                cov_z = np.broadcast_to(cov_z, (N, dz, dz))

            z_next = np.empty((N, dz), dtype=float)
            for i in range(N):
                z_next[i] = rng.multivariate_normal(mean=mu_z[i], cov=cov_z[i])

            z_pred.append(z_next.copy())
            z_pred_curr = z_next.copy()
            z = z_next

    return PFOutputs(
        z_filt=z_filt,
        w_filt=w_filt,
        z_pred=z_pred,
        ess=ess,
        log_evidence=log_evidence,
        cum_log_evidence=np.cumsum(log_evidence),
        log_odds_pred=log_odds_pred,
        log_odds_filt=log_odds_filt,
    )


# ============================================================
# 3) Analysis helpers (heatmaps, branch mass, collapse time, forecast)
# ============================================================

def _hist_row(samples_1d: np.ndarray, edges: np.ndarray, weights: Optional[np.ndarray] = None) -> np.ndarray:
    if weights is None:
        h, _ = np.histogram(samples_1d, bins=edges, density=False)
        h = h.astype(float)
    else:
        w = weights / (weights.sum() + 1e-12)
        h, _ = np.histogram(samples_1d, bins=edges, weights=w, density=False)
        h = h.astype(float)
    h = h / (h.sum() + 1e-12)
    return h

def _auto_edges_from_particles(z_lists: List[np.ndarray], nbins: int, p_lo: float, p_hi: float) -> Tuple[np.ndarray, np.ndarray]:
    allz = np.concatenate([zz[:, 0] for zz in z_lists], axis=0)
    lo = float(np.percentile(allz, p_lo))
    hi = float(np.percentile(allz, p_hi))
    pad = 0.20 * (hi - lo + 1e-9)
    lo -= pad
    hi += pad
    edges = np.linspace(lo, hi, nbins + 1)
    centers = 0.5 * (edges[:-1] + edges[1:])
    return edges, centers

def predictive_heatmap(pf: PFOutputs, nbins: int, p_lo: float, p_hi: float) -> Tuple[np.ndarray, np.ndarray]:
    edges, centers = _auto_edges_from_particles(pf.z_pred, nbins, p_lo, p_hi)
    H = np.zeros((len(pf.z_pred), nbins), dtype=float)
    for t, zp in enumerate(pf.z_pred):
        H[t] = _hist_row(zp[:, 0], edges)
    return H, centers

def filtering_heatmap(pf: PFOutputs, nbins: int, p_lo: float, p_hi: float) -> Tuple[np.ndarray, np.ndarray]:
    edges, centers = _auto_edges_from_particles(pf.z_filt, nbins, p_lo, p_hi)
    H = np.zeros((len(pf.z_filt), nbins), dtype=float)
    for t, (zf, wf) in enumerate(zip(pf.z_filt, pf.w_filt)):
        H[t] = _hist_row(zf[:, 0], edges, weights=wf)
    return H, centers

def branch_mass_curves(pf: PFOutputs) -> Tuple[np.ndarray, np.ndarray]:
    """
    mleft_pred[t] = P(z_t<0 | x_{<t})  using log_odds_pred
    mleft_filt[t] = P(z_t<0 | x_{<=t}) using log_odds_filt
    """
    # log_odds = log((1-m)/m) => m = 1/(1+exp(log_odds))
    mleft_pred = 1.0 / (1.0 + np.exp(pf.log_odds_pred))
    mleft_filt = 1.0 / (1.0 + np.exp(pf.log_odds_filt))
    return mleft_pred, mleft_filt

def collapse_time(mleft: np.ndarray, thresh: float) -> Optional[int]:
    """
    First t (1-based) where mleft < thresh and stays there.
    """
    below = (mleft < thresh)
    if not np.any(below):
        return None
    for i in range(len(mleft)):
        if below[i] and np.all(below[i:]):
            return i + 1
    return int(np.argmax(below)) + 1

def rollout_forecast_from_particles(
    z_particles: np.ndarray,             # (N,1)
    weights: Optional[np.ndarray],       # (N,) or None
    transition: GaussianTransition,
    emission: GaussianEmission,
    extras: Dict,
    *,
    H: int,
    seed: int,
    resample_by_weights: bool = True,
) -> Dict[str, np.ndarray]:
    rng = np.random.default_rng(seed)
    z = z_particles.copy()
    N = z.shape[0]
    dz = z.shape[1]

    if weights is not None and resample_by_weights:
        w = weights / (weights.sum() + 1e-12)
        idx = rng.choice(N, size=N, replace=True, p=w)
        z = z[idx]

    xs = []
    for _h in range(H):
        # z -> z_next
        mu_z = np.asarray(transition.mean_fn(z, extras), dtype=float)
        cov_z = np.asarray(transition.cov_fn(z, extras), dtype=float)
        if cov_z.ndim == 2:
            cov_z = np.broadcast_to(cov_z, (N, dz, dz))
        z_next = np.empty_like(z)
        for i in range(N):
            z_next[i] = rng.multivariate_normal(mean=mu_z[i], cov=cov_z[i])
        z = z_next

        # x | z
        mu_x = np.asarray(emission.mean_fn(z, extras), dtype=float)  # (N,2)
        cov_x = np.asarray(emission.cov_fn(z, extras), dtype=float)  # (2,2) or (N,2,2)
        if cov_x.ndim == 2:
            cov_x = np.broadcast_to(cov_x, (N, 2, 2))
        x_next = np.empty((N, 2), dtype=float)
        for i in range(N):
            x_next[i] = rng.multivariate_normal(mean=mu_x[i], cov=cov_x[i])
        xs.append(x_next)

    X = np.stack(xs, axis=1)  # (N,H,2)
    return {"X": X, "mean": X.mean(axis=0), "var": X.var(axis=0)}


# ============================================================
# 4) Optional (heavy) multimodality diagnostics (kept off by default)
# ============================================================

def bimodality_kurtosis_proxy(z_1d: np.ndarray) -> float:
    z = np.asarray(z_1d, dtype=float)
    m = float(z.mean())
    v = float(((z - m) ** 2).mean() + 1e-12)
    k = float(((z - m) ** 4).mean() / (v ** 2))
    excess = k - 3.0
    return -excess

def two_halves_gap(z_1d: np.ndarray) -> float:
    z = np.sort(np.asarray(z_1d, dtype=float))
    N = len(z)
    left = z[: N // 2]
    right = z[N // 2 :]
    return float(right.mean() - left.mean())


# ============================================================
# 5) Plot helpers + saving
# ============================================================

def _savefig(out_dir: Path, name: str, fig: plt.Figure, dpi: int = 200) -> None:
    fig.savefig(out_dir / name, dpi=dpi, bbox_inches="tight")
    plt.close(fig)

def _write_json(out_dir: Path, name: str, obj: Dict) -> None:
    (out_dir / name).write_text(json.dumps(obj, indent=2))

def _ensure_dir(cfg: Config) -> Path:
    root = Path(cfg.results_root) / cfg.subfolder
    root.mkdir(parents=True, exist_ok=True)
    run = cfg.run_name.strip() or _autoname(cfg)
    out_dir = root / run
    out_dir.mkdir(parents=True, exist_ok=True)
    return out_dir


# ============================================================
# 6) Main
# ============================================================

def main(cfg: Config) -> None:
    out_dir = _ensure_dir(cfg)

    # extras dict passed into generator + PF
    extras = dict(
        a=cfg.a,
        lam=cfg.lam,
        dt=cfg.dt,
        process_noise=cfg.process_noise,
        emit_noise=cfg.emit_noise,
        emission_mode=cfg.emission_mode,
        eps=cfg.eps,
        n_even=cfg.n_even,
        k_tanh=cfg.k_tanh,
    )

    # Save config upfront
    _write_json(out_dir, "config.json", {"cfg": asdict(cfg), "extras": extras})

    # Build stationary generator objects
    prior = GaussianPrior(mu0=np.zeros(cfg.dz), cov0=np.eye(cfg.dz))
    transition = GaussianTransition(mean_fn=trans_mean_potential, cov_fn=trans_cov_isotropic)
    emission = GaussianEmission(mean_fn=emit_mean, cov_fn=emit_cov_isotropic)

    # Generate one trajectory
    batch = generate_sequences(
        T=cfg.T,
        B=cfg.B,
        prior=prior,
        transition=transition,
        emission=emission,
        seed=cfg.seed_data,
        return_logp=False,
        extras=extras,
    )
    x = batch.x[0]        # (T,2)
    z_true = batch.z[0]   # (T,1)

    # Run PF
    pf = bootstrap_pf(
        x_seq=x,
        prior=prior,
        transition=transition,
        emission=emission,
        N=cfg.N,
        seed=cfg.seed_pf,
        extras=extras,
        resample_every=cfg.resample_every,
    )

    # ------------------------------------------------------------
    # Plots
    # ------------------------------------------------------------

    if cfg.do_observation_plots:
        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), x[:, 0], label="x1=z^2 + noise")
        plt.plot(np.arange(1, cfg.T + 1), x[:, 1], label=f"x2 ({cfg.emission_mode})")
        plt.xlabel("t")
        plt.title("Observation channels (sanity)")
        plt.grid(True)
        plt.legend()
        _savefig(out_dir, "observations_timeseries.png", fig)

        fig = plt.figure(figsize=(5, 5))
        plt.scatter(z_true[:, 0], x[:, 1], s=10)
        plt.xlabel("z_true")
        plt.ylabel("x2")
        plt.title("Emission sanity: x2 vs z_true")
        plt.grid(True)
        _savefig(out_dir, "emission_x2_vs_z.png", fig)

    if cfg.do_heatmaps:
        Hpred, zgrid_pred = predictive_heatmap(
            pf, nbins=cfg.heatmap_bins, p_lo=cfg.heatmap_zclip_lo, p_hi=cfg.heatmap_zclip_hi
        )
        fig = plt.figure(figsize=(11, 4))
        plt.imshow(
            Hpred,
            aspect="auto",
            origin="lower",
            extent=[zgrid_pred[0], zgrid_pred[-1], 1, cfg.T - 1],
            interpolation="nearest",
        )
        plt.colorbar(label="density (hist)")
        plt.plot(z_true[1:, 0], np.arange(1, cfg.T), linewidth=2)
        plt.xlabel("z")
        plt.ylabel("t")
        plt.title("Predictive heatmap: p(z_t | x_{<t}) + true z_t")
        plt.grid(False)
        _savefig(out_dir, "heatmap_predictive.png", fig)

        Hfilt, zgrid_filt = filtering_heatmap(
            pf, nbins=cfg.heatmap_bins, p_lo=cfg.heatmap_zclip_lo, p_hi=cfg.heatmap_zclip_hi
        )
        fig = plt.figure(figsize=(11, 4))
        plt.imshow(
            Hfilt,
            aspect="auto",
            origin="lower",
            extent=[zgrid_filt[0], zgrid_filt[-1], 1, cfg.T],
            interpolation="nearest",
        )
        plt.colorbar(label="density (weighted hist)")
        plt.plot(z_true[:, 0], np.arange(1, cfg.T + 1), linewidth=2)
        plt.xlabel("z")
        plt.ylabel("t")
        plt.title("Filtering heatmap: p(z_t | x_{<=t}) + true z_t")
        plt.grid(False)
        _savefig(out_dir, "heatmap_filtering.png", fig)

    if cfg.do_ess:
        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), pf.ess)
        plt.xlabel("t")
        plt.ylabel("ESS")
        plt.title("ESS after weighting with x_t")
        plt.grid(True)
        _savefig(out_dir, "ess_curve.png", fig)

    mleft_pred, mleft_filt = branch_mass_curves(pf)

    if cfg.do_branch_mass:
        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), mleft_pred, label="P(z_t<0 | x_{<t}) (predictive)")
        plt.plot(np.arange(1, cfg.T + 1), mleft_filt, label="P(z_t<0 | x_{<=t}) (filtering)")
        plt.axhline(cfg.left_thresh, linestyle="--", label=f"thresh={cfg.left_thresh:g}")
        plt.xlabel("t")
        plt.ylabel("left-branch mass")
        plt.title("Branch-mass curves")
        plt.grid(True)
        plt.legend()
        _savefig(out_dir, "branch_mass_curves.png", fig)

        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), pf.log_odds_pred, label="log-odds (predictive)")
        plt.plot(np.arange(1, cfg.T + 1), pf.log_odds_filt, label="log-odds (filtering)")
        plt.xlabel("t")
        plt.ylabel("log((1-m)/m)")
        plt.title("Log-odds from branch masses (proxy for likelihood-ratio accumulation)")
        plt.grid(True)
        plt.legend()
        _savefig(out_dir, "branch_log_odds.png", fig)

    if cfg.do_evidence:
        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), pf.log_evidence)
        plt.xlabel("t")
        plt.ylabel("log p(x_t | x_{<t})")
        plt.title("Per-step log evidence increment (PF approximation)")
        plt.grid(True)
        _savefig(out_dir, "log_evidence_per_step.png", fig)

        fig = plt.figure(figsize=(10, 3))
        plt.plot(np.arange(1, cfg.T + 1), pf.cum_log_evidence)
        plt.xlabel("t")
        plt.ylabel("Σ log p(x_s | x_{<s})")
        plt.title("Cumulative log evidence (evidence accumulation)")
        plt.grid(True)
        _savefig(out_dir, "log_evidence_cumulative.png", fig)

    # ------------------------------------------------------------
    # Forecast divergence (mixture vs forced-right) at t_star
    # ------------------------------------------------------------
    forecast_div = None
    if cfg.do_forecast_divergence:
        t_idx = max(1, min(cfg.T, int(cfg.t_star))) - 1  # 0-based
        zt = pf.z_filt[t_idx]
        wt = pf.w_filt[t_idx]

        mix = rollout_forecast_from_particles(
            zt, wt, transition, emission, extras, H=cfg.H_forecast, seed=999, resample_by_weights=True
        )

        mask_right = (zt[:, 0] >= 0.0)
        z_right = zt[mask_right]
        w_right = wt[mask_right]
        if z_right.shape[0] < 25:
            # if branch basically dead, don't crash
            z_right, w_right = zt, wt

        right = rollout_forecast_from_particles(
            z_right, w_right, transition, emission, extras, H=cfg.H_forecast, seed=1001, resample_by_weights=True
        )

        hgrid = np.arange(1, cfg.H_forecast + 1)

        # focus on x2 because it is the "sign channel" in these synthetics
        fig = plt.figure(figsize=(10, 3))
        plt.plot(hgrid, mix["mean"][:, 1], label="mixture forecast mean (x2)")
        plt.plot(hgrid, right["mean"][:, 1], label="forced-right forecast mean (x2)")
        plt.xlabel("horizon h")
        plt.ylabel("E[x2_{t*+h}]")
        plt.title(f"Forecast divergence at t*={cfg.t_star}: mixture vs forced-right")
        plt.grid(True)
        plt.legend()
        _savefig(out_dir, "forecast_divergence_x2_mean.png", fig)

        forecast_div = float(np.sqrt(np.mean((mix["mean"][:, 1] - right["mean"][:, 1]) ** 2)))

    # ------------------------------------------------------------
    # Sensitivity sweeps
    # ------------------------------------------------------------
    resample_results = None
    N_results = None

    if cfg.do_sensitivity:
        # collapse times vs resample_every
        resample_results = []
        for re in cfg.resample_grid:
            pf_re = bootstrap_pf(
                x_seq=x,
                prior=prior,
                transition=transition,
                emission=emission,
                N=cfg.N,
                seed=cfg.seed_pf,
                extras=extras,
                resample_every=int(re),
            )
            _, mleft_f = branch_mass_curves(pf_re)
            c = collapse_time(mleft_f, cfg.left_thresh)
            resample_results.append((int(re), -1 if c is None else int(c)))

        fig = plt.figure(figsize=(8, 3))
        plt.plot([r for r, _ in resample_results], [c for _, c in resample_results], marker="o")
        plt.xlabel("resample_every (0 = never)")
        plt.ylabel(f"collapse time (t where left-mass<{cfg.left_thresh:g})")
        plt.title("Collapse-time sensitivity to resampling frequency")
        plt.grid(True)
        _savefig(out_dir, "sensitivity_resample_every.png", fig)

        # collapse times vs N
        N_results = []
        for N in cfg.N_grid:
            pf_N = bootstrap_pf(
                x_seq=x,
                prior=prior,
                transition=transition,
                emission=emission,
                N=int(N),
                seed=cfg.seed_pf,
                extras=extras,
                resample_every=cfg.resample_every,
            )
            _, mleft_f = branch_mass_curves(pf_N)
            c = collapse_time(mleft_f, cfg.left_thresh)
            N_results.append((int(N), -1 if c is None else int(c)))

        fig = plt.figure(figsize=(8, 3))
        plt.plot([n for n, _ in N_results], [c for _, c in N_results], marker="o")
        plt.xlabel("N particles")
        plt.ylabel(f"collapse time (t where left-mass<{cfg.left_thresh:g})")
        plt.title("Collapse-time sensitivity to particle count")
        plt.grid(True)
        _savefig(out_dir, "sensitivity_particle_count.png", fig)

    # ------------------------------------------------------------
    # Optional “cheap” diagnostics (fast): kurtosis + gap on predictive particles
    # (kept separate from dip/silverman heavy tests)
    # ------------------------------------------------------------
    diag = {}
    if cfg.do_diagnostics:
        # Note: this is still relatively cheap; the heavy tests are not included here.
        # We compute on predictive p(z_t|x_{<t}) using z_pred[t-1].
        kurt = []
        gap = []
        for t in range(1, cfg.T):
            zpt = pf.z_pred[t - 1][:, 0]
            # subsample for speed
            if zpt.size > 5000:
                idx = np.random.default_rng(0).choice(zpt.size, size=5000, replace=False)
                zpt = zpt[idx]
            kurt.append(bimodality_kurtosis_proxy(zpt))
            gap.append(two_halves_gap(zpt))

        diag["kurtosis_proxy"] = np.asarray(kurt, dtype=float)
        diag["gap_proxy"] = np.asarray(gap, dtype=float)

        tgrid = np.arange(1, cfg.T)
        fig = plt.figure(figsize=(10, 3))
        plt.plot(tgrid, diag["kurtosis_proxy"])
        plt.xlabel("t")
        plt.ylabel("-excess kurtosis (predictive)")
        plt.title("Predictive shape proxy vs time")
        plt.grid(True)
        _savefig(out_dir, "diagnostic_kurtosis_proxy.png", fig)

        fig = plt.figure(figsize=(10, 3))
        plt.plot(tgrid, diag["gap_proxy"])
        plt.xlabel("t")
        plt.ylabel("two-halves gap (predictive)")
        plt.title("Predictive separation proxy vs time")
        plt.grid(True)
        _savefig(out_dir, "diagnostic_gap_proxy.png", fig)

    # ------------------------------------------------------------
    # Save arrays + summary
    # ------------------------------------------------------------
    collapse_pred = collapse_time(mleft_pred, cfg.left_thresh)
    collapse_filt = collapse_time(mleft_filt, cfg.left_thresh)

    np.savez(
        out_dir / "results.npz",
        z_true=z_true,
        x=x,
        ess=pf.ess,
        log_evidence=pf.log_evidence,
        cum_log_evidence=pf.cum_log_evidence,
        log_odds_pred=pf.log_odds_pred,
        log_odds_filt=pf.log_odds_filt,
        mleft_pred=mleft_pred,
        mleft_filt=mleft_filt,
        collapse_pred_t=-1 if collapse_pred is None else int(collapse_pred),
        collapse_filt_t=-1 if collapse_filt is None else int(collapse_filt),
        forecast_divergence_x2_mean_l2=(-1.0 if forecast_div is None else float(forecast_div)),
        resample_results=(np.array(resample_results, dtype=float) if resample_results is not None else np.zeros((0, 2))),
        N_results=(np.array(N_results, dtype=float) if N_results is not None else np.zeros((0, 2))),
        # optional diagnostics
        kurtosis_proxy=(diag.get("kurtosis_proxy", np.zeros((0,), dtype=float))),
        gap_proxy=(diag.get("gap_proxy", np.zeros((0,), dtype=float))),
    )

    summary_lines = [
        f"out_dir = {out_dir.resolve()}",
        "",
        "Key readouts:",
        f"  collapse_pred_t (mleft_pred < {cfg.left_thresh:g}) = {collapse_pred}",
        f"  collapse_filt_t (mleft_filt < {cfg.left_thresh:g}) = {collapse_filt}",
    ]
    if forecast_div is not None:
        summary_lines.append(f"  forecast_divergence_x2_mean_l2 @ t*={cfg.t_star}, H={cfg.H_forecast} = {forecast_div:.6f}")
    summary_lines += [
        "",
        "Interpretation tips (what each plot is telling you):",
        "  heatmap_predictive.png:",
        "    - Row t shows p(z_t | x_{<t}) (what you believe *before* seeing x_t).",
        "    - Two bumps early -> genuine ambiguity; collapse later -> disambiguation by evidence.",
        "  heatmap_filtering.png:",
        "    - Row t shows p(z_t | x_{<=t}) (after assimilating x_t).",
        "  ess_curve.png:",
        "    - ESS drops indicate evidence concentrates weight on fewer hypotheses.",
        "  branch_mass_curves.png:",
        "    - Tracks how probability mass migrates from left to right branch (or vice versa).",
        "  log_evidence_per_step.png / log_evidence_cumulative.png:",
        "    - PF approximation of evidence accumulation: log p(x_t|x_{<t}) and cumulative sum.",
        "  branch_log_odds.png:",
        "    - log((1-m)/m) is a simple *odds* proxy; monotone growth indicates accumulating support.",
        "  forecast_divergence_x2_mean.png:",
        "    - If mixture vs forced-branch forecasts differ materially, then ‘keeping both’ matters for forecasting.",
        "",
        "If you don’t see two peaks in predictive heatmap:",
        "  - Usually means the emission is too informative too early (eps too large),",
        "    or dynamics cross the informative region too frequently (dt/lam too high),",
        "    or process_noise is too high (smears modes).",
        "",
    ]
    (out_dir / "summary.txt").write_text("\n".join(summary_lines))

    print("\n".join(summary_lines))


def parse_args() -> Config:
    p = argparse.ArgumentParser()
    # core
    p.add_argument("--T", type=int, default=90)
    p.add_argument("--seed-data", type=int, default=0)
    p.add_argument("--seed-pf", type=int, default=123)
    p.add_argument("--N", type=int, default=30000)
    p.add_argument("--resample-every", type=int, default=3)

    # well params
    p.add_argument("--a", type=float, default=1.0)
    p.add_argument("--lambda", dest="lam", type=float, default=1.0)
    p.add_argument("--dt", type=float, default=0.06)
    p.add_argument("--process-noise", type=float, default=0.18)

    # emission params
    p.add_argument("--emit-noise", type=float, default=0.20)
    p.add_argument("--emission-mode", type=str, default="gated_linear",
                   choices=["gated_linear", "band_evenpower", "tanh_saturate"])
    p.add_argument("--eps", type=float, default=0.50)
    p.add_argument("--n-even", type=int, default=2)
    p.add_argument("--k-tanh", type=float, default=2.5)

    # analysis toggles
    p.add_argument("--no-heatmaps", action="store_true")
    p.add_argument("--no-observations", action="store_true")
    p.add_argument("--no-branch-mass", action="store_true")
    p.add_argument("--no-ess", action="store_true")
    p.add_argument("--no-evidence", action="store_true")
    p.add_argument("--no-forecast", action="store_true")
    p.add_argument("--no-sensitivity", action="store_true")
    p.add_argument("--diagnostics", action="store_true")  # off by default

    # forecast
    p.add_argument("--t-star", type=int, default=55)
    p.add_argument("--H-forecast", type=int, default=20)

    # saving
    p.add_argument("--results-root", type=str, default="results")
    p.add_argument("--subfolder", type=str, default="_synthetic_1d_double_well_analysis")
    p.add_argument("--run-name", type=str, default="")

    args = p.parse_args()

    cfg = Config(
        T=args.T,
        seed_data=args.seed_data,
        seed_pf=args.seed_pf,
        N=args.N,
        resample_every=args.resample_every,
        a=args.a,
        lam=args.lam,
        dt=args.dt,
        process_noise=args.process_noise,
        emit_noise=args.emit_noise,
        emission_mode=args.emission_mode,
        eps=args.eps,
        n_even=args.n_even,
        k_tanh=args.k_tanh,
        do_heatmaps=(not args.no_heatmaps),
        do_observation_plots=(not args.no_observations),
        do_branch_mass=(not args.no_branch_mass),
        do_ess=(not args.no_ess),
        do_evidence=(not args.no_evidence),
        do_forecast_divergence=(not args.no_forecast),
        do_sensitivity=(not args.no_sensitivity),
        do_diagnostics=args.diagnostics,
        t_star=args.t_star,
        H_forecast=args.H_forecast,
        results_root=args.results_root,
        subfolder=args.subfolder,
        run_name=args.run_name,
    )
    return cfg


if __name__ == "__main__":
    cfg = parse_args()
    main(cfg)